export enum USER_PERMS {
  ActionsCollectionGet = 'workflow.actions.collection.get',
  EventsCollectionGet = 'workflow.events.collection.get',
  TasksCollectionGet = 'workflow.tasks.collection.get',
  TasksItemGet = 'workflow.tasks.item.get',
  TasksItemPost = 'workflow.tasks.item.post',
  TasksItemPut = 'workflow.tasks.item.put',
  TasksItemDelete = 'workflow.tasks.item.delete',
  TriggersCollectionGet = 'workflow.triggers.collection.get',
  TriggersItemGet = 'workflow.triggers.item.get',
  TriggersItemPost = 'workflow.triggers.item.post',
  TriggersItemPut = 'workflow.triggers.item.put',
  TriggersItemDelete = 'workflow.triggers.item.delete',
  WorkflowsCollectionGet = 'workflow.workflows.collection.get',
  WorkflowsItemGet = 'workflow.workflows.item.get',
  WorkflowsItemPost = 'workflow.workflows.item.post',
  WorkflowsItemPut = 'workflow.workflows.item.put',
  WorkflowsItemPatch = 'workflow.workflows.item.patch',
  WorkflowsItemDelete = 'workflow.workflows.item.delete',
  WorkflowsItemStartTrigger = 'workflow.workflows.item.startTrigger',
  WorkflowsItemActivate = 'workflow.workflows.item.activate',
  WorkflowsItemDeactivate = 'workflow.workflows.item.deactivate',
  WorkflowsItemTasks = 'workflow.workflows.item.tasks'
}
